[camden]
map_win_multiplier = 1.3

[log]
level = "debug"

[web]
port = 8000

[api]
url = "https://data.vatsim.net/v3/vatsim-data.json"
poll_period = "15s"
timeout = "1s"

[fixed]
data_url = "https://raw.githubusercontent.com/vatsimnetwork/vatspy-data-project/master/VATSpy.dat"
boundaries_url = "https://raw.githubusercontent.com/vatsimnetwork/vatspy-data-project/master/Boundaries.geojson"
runways_url = "https://ourairports.com/data/runways.csv"
geonames_countries_url = "http://download.geonames.org/export/dump/countryInfo.txt"
geonames_shapes_url = "http://download.geonames.org/export/dump/shapes_simplified_low.json.zip"

[track]
uri = "mongodb://localhost:27017"
dbname = "camden-dev"

[cache]
runways = "/tmp/runways.csv.cache"
geonames_countries = "/tmp/geonames-countries.cache"
geonames_shapes = "/tmp/geonames-shapes.cache"
